import TrungQuan from '@/assets/images/TrungQuan.jpeg'
import HoangDung from '@/assets/images/NangTho.jpeg'
import VoiBanDon from '@/assets/images/rain.jpeg'
import BuiAnhTuan from '@/assets/images/BuiAnhTuan.jpeg'

export const songs = [
    {
        id:0,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 14,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:1,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 2,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:2,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 6,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:3,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 3,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:4,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 1,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:5,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 7,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:6,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 11,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:7,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 8,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:8,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 13,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:9,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 4,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:10,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 10,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:11,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 12,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:12,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 5,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:13,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:14,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:15,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:16,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:17,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:18,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:19,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:20,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:21,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:22,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:23,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:24,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:25,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:26,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:27,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:28,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:29,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:30,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:31,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
    {
        id:32,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: TrungQuan,
        likes: 12,
    },
]