

export const songs = [
    {
        id:0,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 14,
    },
    {
        id:1,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 2,
    },
    {
        id:2,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 6,
    },
    {
        id:3,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 3,
    },
    {
        id:4,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 1,
    },
    {
        id:5,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 7,
    },
    {
        id:6,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 11,
    },
    {
        id:7,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 8,
    },
    {
        id:8,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 13,
    },
    {
        id:9,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 4,
    },
    {
        id:10,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 10,
    },
    {
        id:11,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 12,
    },
    {
        id:12,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 5,
    },
    {
        id:13,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
    },
]