import type { Metadata } from "next";
import "./globals.css";
import GlobalHeader from "@/components/layouts/GlobalHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="icon" />
        <title>Music App</title>
      </head>
      <body suppressHydrationWarning={true}>
        <GlobalHeader />
        {children}
      </body>
    </html>
  );
}
