const users = [
  {
    id: 0,
    name: "Minh Tran",
    username: "minhtran1412",
    password: "123456",
    favSongs: [0, 1, 2],
    favPlaylists: [0, 1, 2],
    avatarUrl: "",
  },
  {
    id: 1,
    name: "Minh Tran 1",
    username: "minhtran1412",
    password: "123456",
    favSongs: [3, 4, 5],
    favPlaylists: [3, 4, 5],
    avatarUrl: "",
  },
  {
    id: 2,
    name: "Minh Tran 2",
    username: "minhtran1412",
    password: "123456",
    favSongs: [6, 7, 8],
    favPlaylists: [6, 7, 8],
    avatarUrl: "",
  },
  {
    id: 3,
    name: "Minh Tran 3",
    username: "minhtran1412",
    password: "123456",
    favSongs: [6, 7, 8],
    favPlaylists: [6, 7, 8],
    avatarUrl: "",
  },
];

const artists = [
  {
    id: 0,
    name: "Trung Quân",
    plays: 123,
    image: "",
  },
  {
    id: 1,
    name: "Hoàng Dũng",
    plays: 1234,
    image: "",
  },
  {
    id: 2,
    name: "Voi Bản Đôn",
    plays: 1,
    image: "",
  },
  {
    id: 3,
    name: "Bùi Anh Tuấn",
    plays: 12,
    image: "",
  },
];

const comments = [
  {
    id: 0,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 1,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 2,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 3,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 4,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 5,
        authorId: 0,
        content: "hay qua ban :) 2",
      },
      {
        id: 6,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 7,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 8,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 9,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 10,
        authorId: 0,
        content: "hay qua ban :) 3",
      },
      {
        id: 11,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 12,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 13,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 14,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 15,
        authorId: 0,
        content: "hay qua ban :) 4",
      },
      {
        id: 16,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 17,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 18,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 19,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 20,
        authorId: 0,
        content: "hay qua ban :) 5",
      },
      {
        id: 21,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 22,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 23,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 24,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 25,
        authorId: 0,
        content: "hay qua ban :) 6",
      },
      {
        id: 26,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 27,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 28,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 29,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 30,
        authorId: 0,
        content: "hay qua ban :) 7",
      },
      {
        id: 31,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 1,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 1,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 2,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 2,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 1,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 2,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 3,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 1,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 2,
        authorId: 0,
        content: "hay qua ban :)",
      },
      {
        id: 3,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 4,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 5,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 6,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 7,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 8,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 9,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
  {
    id: 10,
    contents: [
      {
        id: 0,
        authorId: 0,
        content: "hay qua ban :)",
      },
    ],
  },
];

const genres = ["rock", "hip-hop", "ballad", "lofi", "pop"];

const playlists = [
  {
    id: 0,
    name: "Playlist 1",
    genre: "Pop ballad",
    songs: [0, 1],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
    description:
      "HI this is a really long one iDONTTT KNOW HOW YOU CAN FIT ALL OF THIS IN A CONTAINER, YOU MUST USE HIDDEN AND ALL OF THE OTHER ONES TO TAKE THIS BACK A NOTCH THIS IS VERY BAD UI AND WILL MAKE YOUR APPLICATION LOOK LIKE ABSOLUTE HORSE SHIT HORSE SHIT HORSE SHIT SHORSE SHIT HORSE SHIT HORSE SHIT HORSE SHIT HORSE SHIHT",
  },
  {
    id: 1,
    name: "Playlist 2",
    genre: "Rock",
    songs: [2, 3],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
  {
    id: 2,
    name: "Playlist 3",
    genre: "Rock",
    songs: [4, 5],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
  {
    id: 3,
    name: "Playlist 4",
    genre: "Pop ballad",
    songs: [6, 7],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
  {
    id: 4,
    name: "Playlist 5",
    genre: "Pop ballad",
    songs: [8, 9],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
  {
    id: 5,
    name: "Playlist 6",
    genre: "Pop ballad",
    songs: [10, 11],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
  {
    id: 6,
    name: "Playlist 7",
    genre: "Pop ballad",
    songs: [12, 13],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
  {
    id: 7,
    name: "Playlist 8",
    genre: "Pop ballad",
    songs: [0, 1],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
  {
    id: 8,
    name: "Playlist 9",
    genre: "Pop ballad",
    songs: [0, 1],
    image: "rain.jpeg",
    author: "tranhoangminh1412",
  },
];

const songs = [
    {
        id:0,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 14,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:1,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 2,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:2,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 6,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:3,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 3,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:4,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 1,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:5,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 7,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:6,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 11,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:7,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 8,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:8,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 13,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:9,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 4,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:10,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 10,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:11,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 12,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:12,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 5,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:13,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:14,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:15,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:16,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:17,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:18,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:19,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:20,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:21,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:22,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:23,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:24,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:25,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:26,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:27,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:28,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:29,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:30,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:31,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
    {
        id:32,
        name: "Dấu Mưa",
        artist: "Trung Quân",
        length: "3:14",
        plays: 9,
        genre: "rock",
        image: "",
        likes: 12,
    },
]

module.exports = {users,comments,genres,playlists,songs,artists};
